global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

scrape_configs:

  # Prometheus Self Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090

  # Linux Server Metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - server1:9100
          - server2:9100

## Blackbox HTTP Monitoring
#- job_name: 'blackbox_http'
#  metrics_path: /probe
#  params:
#    module: [http_2xx]
#
#  static_configs:
#    - targets:
#        - https://google.com
#        - https://github.com
#
#  relabel_configs:
#    - source_labels: [__address__]
#      target_label: __param_target
#
#    - source_labels: [__param_target]
#      target_label: instance
#
#    - target_label: __address__
#      replacement: localhost:9115
#
## Kubernetes Monitoring
#- job_name: 'kubernetes-nodes'
#  kubernetes_sd_configs:
#    - role: node
